"""update knowledge centre schema

Revision ID: 68eb357d6f64
Revises: 986fea77ddce
Create Date: 2026-06-17 11:44:40.041038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eb357d6f64'
down_revision: Union[str, Sequence[str], None] = '986fea77ddce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_centre', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('category', sa.String(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('author', sa.String(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.drop_column('knowledge_centre', 'published_date')
    op.drop_column('knowledge_centre', 'meta_description')
    op.drop_column('knowledge_centre', 'featured_image')
    op.drop_column('knowledge_centre', 'short_description')
    op.drop_column('knowledge_centre', 'meta_title')
    op.drop_column('knowledge_centre', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_centre', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('meta_title', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('short_description', sa.TEXT(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('featured_image', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('meta_description', sa.TEXT(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('published_date', sa.DATETIME(), nullable=True))
    op.drop_column('knowledge_centre', 'published_at')
    op.drop_column('knowledge_centre', 'is_published')
    op.drop_column('knowledge_centre', 'image_url')
    op.drop_column('knowledge_centre', 'author')
    op.drop_column('knowledge_centre', 'category')
    op.drop_column('knowledge_centre', 'excerpt')
    # ### end Alembic commands ###
