"""Add WebsiteContent model

Revision ID: 986fea77ddce
Revises: e9f585e81df8
Create Date: 2026-06-17 11:02:01.226276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986fea77ddce'
down_revision: Union[str, Sequence[str], None] = 'e9f585e81df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('field_key', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_id'), 'website_content', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_page'), 'website_content', ['page'], unique=False)
    op.create_index(op.f('ix_website_content_section'), 'website_content', ['section'], unique=False)
    op.drop_index(op.f('ix_site_content_section'), table_name='site_content')
    op.drop_table('site_content')
    op.drop_table('contact_info')
    op.drop_table('footer_content')
    op.add_column('knowledge_centre', sa.Column('meta_title', sa.String(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('meta_description', sa.Text(), nullable=True))
    op.drop_column('knowledge_centre', 'category')
    op.drop_column('knowledge_centre', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_centre', sa.Column('author', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_column('knowledge_centre', 'meta_description')
    op.drop_column('knowledge_centre', 'meta_title')
    op.create_table('footer_content',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tagline', sa.TEXT(), nullable=True),
    sa.Column('copyright_text', sa.VARCHAR(), nullable=True),
    sa.Column('logo_image', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_info',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('maps_embed_url', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_content',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('section', sa.VARCHAR(), nullable=False),
    sa.Column('field_key', sa.VARCHAR(), nullable=False),
    sa.Column('field_value', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_section'), 'site_content', ['section'], unique=False)
    op.drop_index(op.f('ix_website_content_section'), table_name='website_content')
    op.drop_index(op.f('ix_website_content_page'), table_name='website_content')
    op.drop_index(op.f('ix_website_content_id'), table_name='website_content')
    op.drop_table('website_content')
    # ### end Alembic commands ###
