"""add_site_content_contact_footer_tables

Revision ID: e9f585e81df8
Revises: 98d5e75cbe8e
Create Date: 2026-06-17 09:50:34.568819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f585e81df8'
down_revision: Union[str, Sequence[str], None] = '98d5e75cbe8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('maps_embed_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('copyright_text', sa.String(), nullable=True),
    sa.Column('logo_image', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_section'), 'site_content', ['section'], unique=False)
    op.add_column('knowledge_centre', sa.Column('category', sa.String(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('author', sa.String(), nullable=True))
    op.drop_column('knowledge_centre', 'meta_description')
    op.drop_column('knowledge_centre', 'meta_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_centre', sa.Column('meta_title', sa.VARCHAR(), nullable=True))
    op.add_column('knowledge_centre', sa.Column('meta_description', sa.TEXT(), nullable=True))
    op.drop_column('knowledge_centre', 'author')
    op.drop_column('knowledge_centre', 'category')
    op.drop_index(op.f('ix_site_content_section'), table_name='site_content')
    op.drop_table('site_content')
    op.drop_table('footer_content')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
